### ISSUE TITLE
No such file or directory  #include "HID.h"

### ISSUE THREAD

**Issue by anonymousethical** [kovinevmv/DigiSparkStealer#4]
Hey, I got a problem when I want to upload the sketch script to my digispark. This is the error I got: 

Arduino:1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board:"Digispark (Default - 16.5mhz)"

In file included from C:\Users\144298\Desktop\DigiSparkStealer-master\arduino_source\sketch\sketch.ino:1:0:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.42.0_x86__mdqgnx93n4wtt\libraries\Keyboard\src/Keyboard.h:25:17: fatal error: HID.h: No such file or directory

 #include "HID.h"

                 ^

compilation terminated.

exit status 1

Error compiling for board Digispark (Default - 16.5mhz)

**Comment by kovinevmv** [comment]
You don’t installed required library for digispark. It’s not my package and error. 

Try to google it. Maybe it will help:
https://github.com/arduino/Arduino/issues/6259
https://forum.arduino.cc/index.php?topic=464872.0

**Comment by hgk8769789** [comment]
@anonymousethical did you solve it?
