### ISSUE TITLE
Getting compile error.

### ISSUE THREAD

**Issue by Tfimanayek** [kovinevmv/DigiSparkStealer#8]
fatal error: HID.h: No such file or directory
 #include "HID.h"
                 
compilation terminated.
exit status 1
Error compiling for board Digispark (Default - 16.5mhz).

helppp

**Comment by kovinevmv** [comment]
Thanks for trying to use my project. Unfortunately, I haven't run it for over 2 years, so I can't tell you what the problem might be. Moreover, I have a lot of other work now and I don't really want to return to the project. I have not encountered such a problem as yours, so I cannot offer a solution. Try installing software and libraries from two years ago, there may be an update issue. In this case, Google is a better assistant than me.

Good luck.

**Comment by Tfimanayek** [comment]
i have solved the problem (uploaded the wrong sketch LOL)
have a great day.
thanks a lot
